# -*- coding: utf-8 -*-
"""Machine Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qipd_lIoCzKVtyMURxfzw5f2XTfTraV6

# Challenge Overview
Objective

In this challenge, you will explore the use of Neural Networks and build a model that translates text from English to French.You will go through key steps in the Data Science Lifecycle to better understand how machine learning can be applied to natural language processing tasks.

Dataset

Download from GitHub RepositoryThe dataset includes paired English and French sentences that will allow you to experiment with translation tasks in both directionsYou’ll use this dataset to build and test your machine translation model.

# Importing Libraries
"""

import pandas as pd
import numpy as np

"""# Loading Data"""

!git clone https://github.com/zaka-ai/machine_learning_certification

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/machine_learning_certification/Challenge 7

"""***Loading Language Datasets***

We’re working with two CSV files—one containing English sentences and the other containing French sentences. Each file should be read into its own dedicated DataFrame:

The English sentences will be loaded into a DataFrame named english

The French sentences will be loaded into a DataFrame named french

This separation allows for easier preprocessing and language-specific handling later on.
"""

eng_path = "/content/machine_learning_certification/Challenge 7/en.csv"
english = pd.read_csv(eng_path, header = None)
english.head()

fr_path = "/content/machine_learning_certification/Challenge 7/fr.csv"
french = pd.read_csv(fr_path, header = None)
french.head()

"""**Counting Sentences in Each Dataset**

To determine how many sentences are contained in each file, we simply need to calculate the length of each DataFrame:

Use len(english) to find the total number of English sentences

Use len(french) to find the total number of French sentences

This step gives us a quick overview of the dataset size for each language, which is essential for managing data preprocessing and model training.
"""

print("we have", len(english), "sentences in the english file")
print("we have", len(french), "sentences in the french file")

"""***Merging Language Datasets***

To streamline processing, we need to combine the two separate DataFrames—english and french—into a single unified DataFrame called df. This new DataFrame will include:

One column containing the French sentences

One column containing the corresponding English sentences

This format ensures that each row represents a parallel translation pair, simplifying tasks such as training translation models or evaluating accuracy.
"""

df = pd.concat([french, english], axis = 1)
df.head()

"""***Naming Columns for Easy Access***

To simplify data handling and improve readability, we’ll assign descriptive names to the columns in our combined DataFrame df. This will allow us to access each language's sentences easily using:

"French" for the column containing French sentences

"English" for the column containing English sentences

Clear column names make code cleaner and analysis more intuitive.
"""

df.columns = ['French', 'English']
df.head()

"""***Sampling a Random Translation Pair***

To verify the quality of the translations, we’ll randomly select a row from the merged DataFrame df and print both the French and English sentences.

This quick check helps us confirm whether the translation pairs are properly aligned and make intuitive sense.
"""

print ( "English: ", df['English'][5])
print ( "French: ", df['French'][5])

"""# Cleaning Data

The dataset is mostly tidy, but we still need to strip away any punctuation.
"""

import regex as re

def remove_punc(text):
  return re.sub(r'[.!?:;,]', '', text)

df['English'] = df['English'].apply(lambda x: remove_punc(x))
df['French'] = df['French'].apply(lambda x:remove_punc(x))
print ( "English: ", df['English'][5])
print ( "French: ", df['French'][5])

"""# Exploring Data

***Counting Words in Each Sentence***

We need to add a new column to the dataset that indicates how many words are in each sentence — for both English and French.
"""

df['English_len'] = df['English'].apply(lambda x: len(x.split()))
df['French_len'] = df['French'].apply(lambda x: len(x.split()))
df.head()

"""***Visualizing Sentence Length Distributions***

We need to create visualizations that show how sentence lengths are distributed in both the English and French datasets.
"""

import matplotlib.pyplot as plt
df['English_len'].hist()
plt.title('Distribution of English lengths')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()

df['French_len'].hist()
plt.title('Distribution of French lengths')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()

"""***Identifying Maximum Sentence Lengths***

French sentences generally appear longer than their English counterparts. For instance, English sentences often cap at around 14 words, while French ones can easily reach 20.

To improve accuracy, we'll determine the maximum word count for each language separately.
"""

max_eng = df['English_len'].max()
max_fr = df['French_len'].max()
print('So the English Sentence that has the greatest number of words is made of', max_eng, 'words, while the French Sentence that has the greatest number of words is made of ', max_fr, ' words')

"""# Preprocessing Data


Before processing the data, we need to tokenize and pad it appropriately. Since the dataset includes both English and French texts, we cannot use a single tokenizer for both languages.

Each tokenizer is designed to handle a specific language and relies on a unique vocabulary or dictionary tailored to that language. These dictionaries cannot be combined or merged.

🔹 Therefore, we must use:

* An English-specific tokenizer for English data

* A French-specific tokenizer for French data
"""

from tensorflow.keras.preprocessing.text import Tokenizer

eng_tokenizer = Tokenizer()
eng_tokenizer.fit_on_texts(df['English'])

fr_tokenizer = Tokenizer()
fr_tokenizer.fit_on_texts(df['French'])

"""***Converting Text into Numerical Sequences***

Once the data is tokenized, the next step is to fit it onto the dataset. This involves transforming the text using the texts_to_sequences method, which converts each word into its corresponding numerical representation based on the tokenizer’s vocabulary.

 In other words:

* Every word is mapped to a specific number

* This transformation prepares the data for input into machine learning models
"""

fr_tokenized = fr_tokenizer.texts_to_sequences(df['French'])
eng_tokenized = eng_tokenizer.texts_to_sequences(df['English'])

"""***Determining the Vocabulary Size per Language***


To identify the number of unique words in both English and French, we need to access the word_index attribute of each tokenizer individually.

✅ That means:

* Use the English tokenizer's word_index to count unique English tokens

* Use the French tokenizer's word_index to count unique French tokens

Each tokenizer builds its own vocabulary based on the data it's trained on, so this step helps us understand the scope of each language's representation in the dataset.
"""

eng_vocab_size = len(eng_tokenizer.word_index)
fr_vocab_size = len(fr_tokenizer.word_index)
print("English Vocabulary Size:", eng_vocab_size)
print("French Vocabulary Size:", fr_vocab_size)

"""***Padding Sequences for Uniform Length***

To ensure all sentences have the same length, we’ll apply padding — specifically post-padding, where zeros are added at the end of each sentence.

Since English sentences reach a maximum of 15 words and French ones up to 21, it's logical to pad each set to its respective maximum length. This way, we preserve the full sentence structure while standardizing the sequence lengths for model training or analysis.
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences

fr_tokenized_padded = pad_sequences(fr_tokenized, maxlen = max_fr, padding = 'post')
eng_tokenized_padded = pad_sequences(eng_tokenized, maxlen = max_eng, padding = 'post')

"""# Modeling

***Building a Seq2Seq Architecture***

After preprocessing the data, we can proceed to design the model using recurrent layers such as RNNs, LSTMs, or GRUs. A good starting point is exploring how to construct a Sequence-to-Sequence (Seq2Seq) model, which introduces key components and specialized layers for translation tasks.

The core idea of this architecture is to take an English sentence as input and generate its French translation as output.

🔹 Encoder

Embedding Layer:

Accepts the English sentence and maps each word to its corresponding embedding vector.

We specify:

The vocabulary size

The embedding dimension

The input sentence length

GRU Layer (or LSTM/RNN):

Processes the embeddings and produces a context vector summarizing the sentence.

This marks the end of the encoder phase.

🔸 Decoder
RepeatVector Layer:

Takes the context vector and repeats it for the number of time steps equal to the maximum French sentence length.

GRU Layer:

Predicts the output sequence step by step across the repeated context vector.

TimeDistributed Dense Layer + Softmax:

At each time step, a word in French is predicted.

The Dense layer (shared across all time steps) applies a softmax over the entire French vocabulary to select the most appropriate word.
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, RepeatVector, TimeDistributed, Dense


test_model = Sequential()
test_model.add(Embedding(eng_vocab_size+1, 100, input_length=max_eng))
test_model.add(GRU(20))
test_model.add(RepeatVector(max_fr))
test_model.add(GRU(20, return_sequences=True))
test_model.add(TimeDistributed(Dense(fr_vocab_size+1, activation='softmax')))
test_model.summary()


model = Sequential()

# Input layer with explicit shape
model.add(Embedding(
    input_dim=eng_vocab_size,
    output_dim=100,  # Increased embedding dimension
    input_length=max_eng
))

model.add(GRU(20))
model.add(RepeatVector(max_fr))
model.add(GRU(20, return_sequences=True))
model.add(TimeDistributed(Dense(fr_vocab_size+1, activation='softmax')))

# 4. Force model build with concrete batch size
model.build(input_shape=(32, max_eng))  # 32 = typical batch size

# 5. Final summary
model.summary()

"""***Compiling and Training the Translation Model***

When compiling the model, we use sparse categorical crossentropy as the loss function. This choice is appropriate because our target sequences (the output labels) are represented as integers rather than one-hot encoded vectors. Sparse categorical crossentropy handles this format directly, offering faster computation—though it may sacrifice a bit of accuracy compared to its standard counterpart.

For training, we fit the model on our training dataset while reserving a validation split. This helps monitor the model’s performance and allows for fine-tuning based on validation feedback.

📉 A quick note on evaluation: Although accuracy is often visualized during training, it's not ideal for translation models. That’s because accuracy demands an exact match between predicted and reference sentences. Even a single-word difference would result in a failed match, making it too strict for evaluating translations.

Instead, alternative metrics like BLEU, ROUGE, or METEOR are commonly used in machine translation to measure how close a generated sentence is to the human reference.
"""

model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model.fit(x= eng_tokenized_padded, y=fr_tokenized_padded, validation_split=0.2, epochs = 25, batch_size = 64)

"""***Alternative Loss Function Strategy***

Alternatively, we can apply one-hot encoding to our target sequences and use the standard categorical crossentropy as the loss function. This method represents each token with a vector where the correct class is marked with a 1 and the rest are zeros. It tends to be more precise in certain cases, especially when dealing with multi-class classification tasks—though it's slightly more computationally demanding than sparse categorical crossentropy
"""

from tensorflow.keras.utils import to_categorical

# First calculate proper vocab size
fr_vocab_size = max(fr_tokenizer.word_index.values()) + 1

# Then convert to categorical
fr_tokenized_padded_encoded = to_categorical(
    fr_tokenized_padded,
    num_classes=fr_vocab_size
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, RepeatVector, TimeDistributed, Dense, Bidirectional

model_new = Sequential()

# Remove +1 from vocab sizes (should already include padding)
model_new.add(Embedding(eng_vocab_size+1, 100, input_length=max_eng))

model_new.add(GRU(20))
model_new.add(RepeatVector(max_fr))
model_new.add(GRU(20, return_sequences=True))
model_new.add(TimeDistributed(Dense(fr_vocab_size+1, activation='softmax')))

# Force build with explicit batch shape
model_new.build(input_shape=(None, max_eng))  # None = variable batch size
model_new.summary()

model_new.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model_new.fit(x= eng_tokenized_padded, y=fr_tokenized_padded, validation_split=0.2, epochs = 25, batch_size = 64)

"""***Generating Translations from English to French***

Once the model is built and trained, the next step is to define a function that accepts an input sentence in English and produces the corresponding translated sentence in French.
"""

def final_predictions_model1(sentence):

  y_id_to_word = {value: key for key, value in fr_tokenizer.word_index.items()}
  y_id_to_word [0] = '<PAD>'

  sentence = eng_tokenizer.texts_to_sequences([sentence])

  sentence = pad_sequences(sentence, maxlen = max_eng, padding = 'post')

  predictions = model_new.predict(sentence)

  print(' '.join([y_id_to_word[np.argmax(x)] for x in predictions[0]]))

"""***Evaluating Sample Sentences***

We now move on to testing the model with a set of example sentences to assess its translation quality.
"""

input = "she is driving the truck"

final_predictions_model1(input)

"""***Enhancing Translation with Bidirectional Architecture***

The initial translation output isn’t as accurate as desired, so we’ll refine the model by adjusting its architecture to incorporate bidirectionality—a powerful approach for machine translation tasks.

To implement this improvement, we’ll build a second model, named model_2, which leverages a Bidirectional RNN (such as Bidirectional GRU or LSTM) in the encoder. This allows the model to process context from both past and future tokens simultaneously, leading to richer representations and more fluent translations.
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, RepeatVector, TimeDistributed, Dense, Bidirectional

model2= Sequential()

# Remove +1 from vocab sizes (should already include padding)
model2.add(Embedding(eng_vocab_size+1, 100, input_length=max_eng))

model2.add(Bidirectional(GRU(20)))
model2.add(RepeatVector(max_fr))
model2.add(Bidirectional(GRU(256, return_sequences=True)))
model2.add(TimeDistributed(Dense(fr_vocab_size+1, activation='softmax')))

# Force build with explicit batch shape
model2.build(input_shape=(None, max_eng))  # None = variable batch size
model2.summary()

model2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model2.fit(x= eng_tokenized_padded, y=fr_tokenized_padded, validation_split=0.2, epochs = 25, batch_size = 64)

def final_predictions_model2(sentence):

  y_id_to_word = {value: key for key, value in fr_tokenizer.word_index.items()}
  y_id_to_word [0] = '<PAD>'

  sentence = eng_tokenizer.texts_to_sequences([sentence])

  sentence = pad_sequences(sentence, maxlen = max_eng, padding = 'post')

  predictions = model2.predict(sentence)

  print(' '.join([y_id_to_word[np.argmax(x)] for x in predictions[0]]))

input = "she is driving the truck"

final_predictions_model2(input)

"""Step 1 — Export your trained model + tokenizers (one-time)"""

import os, json, pickle
import tensorflow as tf

def export(model2, eng_tokenizer, fr_tokenizer, max_eng, max_fr, out_dir="models"):
    os.makedirs(out_dir, exist_ok=True)

    # Save model
    trained_model.save(os.path.join(out_dir, "translator_model.keras"))

    # Save tokenizers
    with open(os.path.join(out_dir, "eng_tokenizer.pkl"), "wb") as f:
        pickle.dump(eng_tokenizer, f)

    with open(os.path.join(out_dir, "fr_tokenizer.pkl"), "wb") as f:
        pickle.dump(fr_tokenizer, f)

    # Save metadata
    meta = {"max_eng": int(max_eng), "max_fr": int(max_fr)}
    with open(os.path.join(out_dir, "metadata.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)

    print("✅ Export done:", out_dir)

"""Step 2 — Project folder structure"""

!mkdir -p mt-flask-docker/models
!mkdir -p mt-flask-docker/templates
!mkdir -p mt-flask-docker/static

!touch mt-flask-docker/app.py
!touch mt-flask-docker/requirements.txt
!touch mt-flask-docker/Dockerfile
!touch mt-flask-docker/templates/index.html
!touch mt-flask-docker/static/style.css

!find mt-flask-docker -maxdepth 2 -type f

import os, json, pickle
import tensorflow as tf

# CHANGE THIS to your actual trained model variable
trained_model = model2   # or model_new

# These must already exist from training
# eng_tokenizer, fr_tokenizer, max_eng, max_fr

os.makedirs("mt-flask-docker/models", exist_ok=True)

trained_model.save("mt-flask-docker/models/translator_model.keras")

with open("mt-flask-docker/models/eng_tokenizer.pkl", "wb") as f:
    pickle.dump(eng_tokenizer, f)

with open("mt-flask-docker/models/fr_tokenizer.pkl", "wb") as f:
    pickle.dump(fr_tokenizer, f)

with open("mt-flask-docker/models/metadata.json", "w") as f:
    json.dump({
        "max_eng": int(max_eng),
        "max_fr": int(max_fr)
    }, f)

print("✅ Model + tokenizers exported successfully")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mt-flask-docker/app.py
# import json
# import pickle
# import numpy as np
# import tensorflow as tf
# from flask import Flask, render_template, request
# from tensorflow.keras.preprocessing.sequence import pad_sequences
# 
# app = Flask(__name__)
# 
# model = tf.keras.models.load_model("models/translator_model.keras")
# 
# with open("models/eng_tokenizer.pkl", "rb") as f:
#     eng_tokenizer = pickle.load(f)
# 
# with open("models/fr_tokenizer.pkl", "rb") as f:
#     fr_tokenizer = pickle.load(f)
# 
# with open("models/metadata.json", "r") as f:
#     meta = json.load(f)
# 
# MAX_ENG = meta["max_eng"]
# MAX_FR = meta["max_fr"]
# 
# fr_id_to_word = {v: k for k, v in fr_tokenizer.word_index.items()}
# fr_id_to_word[0] = ""
# 
# def translate(text):
#     seq = eng_tokenizer.texts_to_sequences([text.lower()])
#     seq = pad_sequences(seq, maxlen=MAX_ENG, padding="post")
#     preds = model.predict(seq, verbose=0)[0]
#     tokens = np.argmax(preds, axis=1)
# 
#     words = []
#     for t in tokens:
#         w = fr_id_to_word.get(t, "")
#         if w == "":
#             break
#         words.append(w)
#     return " ".join(words)
# 
# @app.route("/", methods=["GET", "POST"])
# def index():
#     src, out = "", ""
#     if request.method == "POST":
#         src = request.form.get("src_text", "")
#         out = translate(src)
#     return render_template("index.html", src=src, translation=out)
# 
# if __name__ == "__main__":
#     app.run(host="0.0.0.0", port=8080)
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mt-flask-docker/templates/index.html
# <!doctype html>
# <html>
# <head>
#   <title>English → French Translator</title>
# </head>
# <body>
#   <h2>English → French Translator</h2>
#   <form method="POST">
#     <textarea name="src_text" rows="4" cols="60">{{ src }}</textarea><br><br>
#     <button type="submit">Translate</button>
#   </form>
# 
#   {% if translation %}
#     <h3>French Translation:</h3>
#     <p>{{ translation }}</p>
#   {% endif %}
# </body>
# </html>
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mt-flask-docker/requirements.txt
# flask
# tensorflow
# numpy
# gunicorn
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mt-flask-docker/Dockerfile
# FROM python:3.10-slim
# 
# WORKDIR /app
# 
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
# 
# COPY . .
# 
# EXPOSE 8080
# CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:app"]
#

!zip -r mt-flask-docker.zip mt-flask-docker

!zip -r mt-flask-docker.zip mt-flask-docker